Adds SYCL asynchronous error handler
argonne-lcf/libCEED pull request #30
Opened 2023-02-08 02:42 UTC by uumesh

Closes #9

2023-02-08 02:46 UTC, uumesh commented
Current implementation adds the asyncHandler to the queue. Optionally we could add it to the context as well.

2023-02-15 20:44 UTC, kris-rowe requested changes

2023-02-15 20:44 UTC, kris-rowe commented on backends/sycl/ceed-sycl-common.sycl.cpp
> +        std::strcat(error_msg, e.what());
If the error message returned by `e.what()` is too long, using `strcat` could cause issues.
Let's use a `std::ostringstream` to build the error message and then pass `error_msg.str()` to `CeedError`.

2023-02-16 17:35 UTC, kris-rowe approved these changes

2023-02-16 17:45 UTC, merged